In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# Loading Dataset


In [ ]:
df=pd.read_csv('/content/Dataset_English_Hindi.csv', encoding='UTF-8')


#Data Analysis

In [ ]:
df.head(10)

English          Hindi
0    Help!          बचाओ!
1    Jump.          उछलो.
2    Jump.          कूदो.
3    Jump.         छलांग.
4   Hello!        नमस्ते।
5   Hello!       नमस्कार।
6  Cheers!       वाह-वाह!
7  Cheers!        चियर्स!
8  Got it?  समझे कि नहीं?
9  I'm OK.   मैं ठीक हूँ।

In [ ]:
df['Hindi_words']=df['Hindi'].str.split().str.len()
df['English_words']=df['English'].str.split().str.len()

In [ ]:
df.head(10)

English          Hindi  Hindi_words  English_words
0    Help!          बचाओ!          1.0              1
1    Jump.          उछलो.          1.0              1
2    Jump.          कूदो.          1.0              1
3    Jump.         छलांग.          1.0              1
4   Hello!        नमस्ते।          1.0              1
5   Hello!       नमस्कार।          1.0              1
6  Cheers!       वाह-वाह!          1.0              1
7  Cheers!        चियर्स!          1.0              1
8  Got it?  समझे कि नहीं?          3.0              2
9  I'm OK.   मैं ठीक हूँ।          3.0              2

In [ ]:
df=df[(df['English_words']<6)&(df['Hindi_words']<6)]

In [ ]:
df.head(10)

English          Hindi  Hindi_words  English_words
0    Help!          बचाओ!          1.0              1
1    Jump.          उछलो.          1.0              1
2    Jump.          कूदो.          1.0              1
3    Jump.         छलांग.          1.0              1
4   Hello!        नमस्ते।          1.0              1
5   Hello!       नमस्कार।          1.0              1
6  Cheers!       वाह-वाह!          1.0              1
7  Cheers!        चियर्स!          1.0              1
8  Got it?  समझे कि नहीं?          3.0              2
9  I'm OK.   मैं ठीक हूँ।          3.0              2

In [ ]:
df=df.drop_duplicates()

In [ ]:
df['Hindi_words']=df['Hindi_words'].astype('int')
df['English_words']=df['English_words'].astype('int')

In [ ]:
df

English  \
0                                   Help!   
1                                   Jump.   
2                                   Jump.   
3                                   Jump.   
4                                  Hello!   
...                                   ...   
24774                 for the first time.   
24781                 United Kingdom: 212   
24787           The answer is probably NO   
24793             that you may recognize.   
24802  Gujrat- Focusnews-place on Gujarat   

                                         Hindi  Hindi_words  English_words  
0                                        बचाओ!            1              1  
1                                        उछलो.            1              1  
2                                        कूदो.            1              1  
3                                       छलांग.            1              1  
4                                      नमस्ते।            1              1  
...                                        ...          ...            ...  
24774                               पहली बार |            3              4  
24781                    यूनाइटेड किंगडम : २१२            4              3  
24787                            शायद नहीं है।            3              5  
24793                    जो आप पहचान सकते हैं.            5              4  
24802  गुजरात - गुजरात पर केन्द्रितसमाचार-स्थल            5              4  

[3308 rows x 4 columns]

In [ ]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(df,test_size=0.02,random_state=0)

In [ ]:
train

English                  Hindi  Hindi_words  \
12403  The mathematics of uncertainty,  असंभावितता की गणित का            4   
18424                       Hindu Wiki            हिन्दू विकि            2   
7856                       Main typed'          प्रमुख टाइपैड            2   
19440                Bareilly District             बरेली जिला            2   
1548   Give me your attention, please.     कृपया ध्यान दीजिए।            3   
...                                ...                    ...          ...   
3184                    one-upmanship.           होड़ चली है.            3   
24475                  You can't share   आप शेयर नहीं कर सकते            5   
9815                           unnayan                 उन्नयन            1   
18416                  But I must say,     लेकिन मैं बताऊंगा,            3   
19621           And we went to Ladakh,      और हम लद्दाख गये,            4   

       English_words  
12403              4  
18424              2  
7856               2  
19440              2  
1548               5  
...              ...  
3184               1  
24475              3  
9815               1  
18416              4  
19621              5  

[3241 rows x 4 columns]

In [ ]:
train1,validation=train_test_split(train,test_size=0.02,random_state=0)

In [ ]:
train1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3176 entries, 639 to 262
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   English        3176 non-null   object
 1   Hindi          3176 non-null   object
 2   Hindi_words    3176 non-null   int64 
 3   English_words  3176 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 124.1+ KB


In [ ]:
train1['English'].str.split(expand=True).stack().value_counts()

the             236
of              212
is              205
a               145
I               136
               ... 
Cause             1
ringing?          1
son.              1
Harivanshray      1
near              1
Length: 4583, dtype: int64

In [ ]:
train1['Hindi'].str.split(expand=True).stack().value_counts()

है।         206
और          173
के          128
यह          121
में         105
           ... 
वैसी          1
भरनी।         1
Ved           1
Pratap        1
आस-पड़ोस      1
Length: 3987, dtype: int64

#Data Processing

In [ ]:
train1['Hindi']=train1['Hindi'].apply(lambda x:'<start> '+ x +' <end>')
train1['English']=train1['English'].apply(lambda x:'<start> '+ x +' <end>')
validation['Hindi']=validation['Hindi'].apply(lambda x:'<start> '+ x +' <end>')
validation['English']=validation['English'].apply(lambda x:'<start> '+ x +' <end>')

In [ ]:
train1.head(10)

English  \
639         <start> He writes beautifully. <end>   
4844         <start> Brahm Vaivart Grantha <end>   
122                 <start> Is that a cat? <end>   
699         <start> You didn't understand. <end>   
7721                <start> Worship period <end>   
10322  <start> Keep the sacredness of life <end>   
8198   <start> Solar transformation/change <end>   
19564       <start> Developmental disorder <end>   
124                 <start> It's for free. <end>   
11392    <start> Attorney-General of India <end>   

                                          Hindi  Hindi_words  English_words  
639            <start> वह सुंदर लिखता है। <end>            4              3  
4844          <start> ब्रह्म वैवर्त पुराण <end>            3              3  
122            <start> वह बिल्ली है क्या? <end>            4              4  
699                <start> तुम समझे नहीं। <end>            3              3  
7721                    <start> भक्ति काल <end>            2              2  
10322  <start> जीवन की पवित्रता बनाए रखना <end>            5              5  
8198                 <start> सौर परिवर्तन <end>            2              2  
19564          <start> विकास संबंधी विकार <end>            3              2  
124              <start> यह मुफ़्त का है। <end>            4              3  
11392        <start> भारत का महान्यायवादी <end>            3              3

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
Eng_token=Tokenizer(filters='',lower=False)
Eng_token.fit_on_texts(list(train1['English']))
Eng_tokenized=Eng_token.texts_to_sequences(list(train1['English']))
Eng_padding=pad_sequences(Eng_tokenized,padding='post')

In [ ]:
Hindi_token=Tokenizer(filters='',lower=False)
Hindi_token.fit_on_texts(list(train1['Hindi']))
Hindi_tokenized=Hindi_token.texts_to_sequences(list(train1['Hindi']))
Hindi_padding=pad_sequences(Hindi_tokenized,padding='post')

In [ ]:
Eng_padding

array([[   1,   13, 1148, ...,    2,    0,    0],
       [   1,  562, 1150, ...,    2,    0,    0],
       [   1,   64,   17, ..., 1151,    2,    0],
       ...,
       [   1,   39, 4583, ...,    2,    0,    0],
       [   1, 4584,    2, ...,    0,    0,    0],
       [   1,    7,  561, ...,  178,    2,    0]], dtype=int32)

In [ ]:
number_of_input_token=len(Eng_token.word_index) #English
number_of_output_token=len(Hindi_token.word_index) #Hindi

In [ ]:
number_of_output_token

3989

In [ ]:
number_of_input_token

4585

In [ ]:
Eng_train=list(train1['English'])
Hindi_train=list(train1['Hindi'])

In [ ]:
Eng_train[2]

'<start> Is that a cat? <end>'

In [ ]:
Eng_padding[2]

array([   1,   64,   17,    6, 1151,    2,    0], dtype=int32)

In [ ]:
english_train_vecs=np.array(Eng_padding)
hindi_train_vecs=np.array(Hindi_padding)

In [ ]:
hindi_train_vecs

array([[   1,   15,  478, ...,    3,    2,    0],
       [   1,  207,  752, ...,    2,    0,    0],
       [   1,   15,  753, ...,   29,    2,    0],
       ...,
       [   1,   49,   97, ..., 1367,    2,    0],
       [   1, 1191,    2, ...,    0,    0,    0],
       [   1,   10, 3989, ...,  527,   22,    2]], dtype=int32)

In [ ]:
english_train_vecs

array([[   1,   13, 1148, ...,    2,    0,    0],
       [   1,  562, 1150, ...,    2,    0,    0],
       [   1,   64,   17, ..., 1151,    2,    0],
       ...,
       [   1,   39, 4583, ...,    2,    0,    0],
       [   1, 4584,    2, ...,    0,    0,    0],
       [   1,    7,  561, ...,  178,    2,    0]], dtype=int32)

#Saving preprocessed data


In [ ]:
np.save('english_train_vecs.npy',english_train_vecs)
np.save('hindi_train_vecs.npy',hindi_train_vecs)

In [ ]:
def load_decoder_inputs(decoder_np_vecs='hindi_train_vecs.npy'):
    vectorized_title=np.load(decoder_np_vecs)
    decoder_input_data=vectorized_title[:,:-1]
    decoder_target_data=vectorized_title[:,1:]
    print(f'Shape of the decoder input:{decoder_input_data.shape}')
    print(f'Shape of the decoder target :{decoder_target_data.shape}')
    return decoder_input_data,decoder_target_data


In [ ]:
decoder_input_data,decoder_target_data=load_decoder_inputs('hindi_train_vecs.npy')

Shape of the decoder input:(3176, 6)
Shape of the decoder target :(3176, 6)


In [ ]:
def load_encoder_inputs(encoder_np_vecs='english_train_vecs.npy'):
    vectorized_body=np.load(encoder_np_vecs)
    encoder_input_data=vectorized_body
    doc_length=encoder_input_data.shape[1]
    print(f'Shape of the encoder input:{encoder_input_data.shape}')
    return encoder_input_data ,doc_length


In [ ]:
encoder_input_data,doc_length=load_encoder_inputs('english_train_vecs.npy')

Shape of the encoder input:(3176, 7)


In [ ]:
from keras.models import Model
from keras.layers import Input,LSTM,GRU,Dense,Embedding,Bidirectional,BatchNormalization
from keras import optimizers

#Model Architecture

In [ ]:
latent_dim=300
encoder_inputs=Input(shape=(doc_length,),name='Encoder-Input')
x=Embedding(number_of_input_token+1,latent_dim,name='Body-Word-Embedding',mask_zero=False)(encoder_inputs)
x=BatchNormalization(name='Encoder-Batchnorm-1')(x)
_,state_h=GRU(latent_dim,return_state=True,name='Encoder-Last-GRU')(x)
encoder_model=Model(inputs=encoder_inputs,outputs=state_h,name='Encoder-Model')
seq2seq_encoder_out=encoder_model(encoder_inputs)


decoder_input=Input(shape=(None,),name='Decoder-Input')
dec_emb=Embedding(number_of_output_token+1,latent_dim,name='Decoder-Word-Embedding',mask_zero=False)(decoder_input)
dec_bn=BatchNormalization(name='Decoder-Batchnorm-1')(dec_emb)

decoder_gru=GRU(latent_dim,return_state=True,return_sequences=True,name='Decoder-GRU')
decoder_gru_output,_=decoder_gru(dec_bn,initial_state=seq2seq_encoder_out)
x=BatchNormalization(name='Decoder-Batchnorm-2')(decoder_gru_output)

decoder_dense=Dense(number_of_output_token+1,activation='softmax',name='Final-Output-Dense')
decoder_outputs=decoder_dense(x)


seq2seq_Model=Model([encoder_inputs,decoder_input],decoder_outputs)
seq2seq_Model.compile(optimizer=optimizers.Nadam(lr=0.001),loss='sparse_categorical_crossentropy',)


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/nadam.py:89: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [ ]:
seq2seq_Model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 Decoder-Input (InputLayer)     [(None, None)]       0           []                               
                                                                                                  
 Decoder-Word-Embedding (Embedd  (None, None, 300)   1197000     ['Decoder-Input[0][0]']          
 ing)                                                                                             
                                                                                                  
 Encoder-Input (InputLayer)     [(None, 7)]          0           []                               
                                                                                                  
 Decoder-Batchnorm-1 (BatchNorm  (None, None, 300)   1200        ['Decoder-Word-Embedding[0][0

In [ ]:
from keras.callbacks import CSVLogger,ModelCheckpoint
script_name_base='seq2seq'
csv_logger=CSVLogger('{:}.log'.format(script_name_base))
model_checkpoint=ModelCheckpoint('{:}.epoch{{epoch:02d}}-val{{val_loss:.5f}}.hdf5'.format(script_name_base),save_best_only=True)
batch_size=100
epochs=50
history=seq2seq_Model.fit([encoder_input_data,decoder_input_data], np.expand_dims(decoder_target_data,axis=1),batch_size=batch_size,epochs=epochs,validation_split=0.12,
                          callbacks=[csv_logger,model_checkpoint])

Epoch 1/50
28/28 [==============================] - 25s 564ms/step - loss: 5.2723 - val_loss: 7.9486
Epoch 2/50
28/28 [==============================] - 12s 447ms/step - loss: 3.8256 - val_loss: 7.9369
Epoch 3/50
28/28 [==============================] - 11s 405ms/step - loss: 3.0995 - val_loss: 7.8929
Epoch 4/50
28/28 [==============================] - 11s 395ms/step - loss: 2.2241 - val_loss: 7.8279
Epoch 5/50
28/28 [==============================] - 12s 443ms/step - loss: 1.3599 - val_loss: 7.7426
Epoch 6/50
28/28 [==============================] - 8s 302ms/step - loss: 0.6721 - val_loss: 7.6515
Epoch 7/50
28/28 [==============================] - 12s 433ms/step - loss: 0.2961 - val_loss: 7.5112
Epoch 8/50
28/28 [==============================] - 10s 349ms/step - loss: 0.1520 - val_loss: 7.3533
Epoch 9/50
28/28 [==============================] - 10s 367ms/step - loss: 0.1004 - val_loss: 7.1563
Epoch 10/50
28/28 [==============================] - 12s 418ms/step - loss: 0.0754 - val_los

In [ ]:
seq=seq2seq_Model.load_weights('/content/seq2seq.epoch23-val3.60886.hdf5')

In [ ]:
def extract_encoder_model(model):
  encoder_model=model.get_layer('Encoder-Model')
  return encoder_model

def extract_decoder_model(model):
     latent_dim=model.get_layer('Decoder-Word-Embedding').output_shape[-1]

     decoder_input=model.get_layer('Decoder-Input').input
     dec_emb=model.get_layer('Decoder-Word-Embedding')(decoder_input)
     dec_bn=model.get_layer('Decoder-Batchnorm-1')(dec_emb)



     gru_inference_state_input=Input(shape=(latent_dim,), name='hidden_states_input')

     gru_out,gru_state_out=model.get_layer('Decoder-GRU')([dec_bn,gru_inference_state_input])

     dec_bn2=model.get_layer('Decoder-Batchnorm-2')(gru_out)
     dense_out=model.get_layer('Final-Output-Dense')(dec_bn2)
     decoder_model=Model([decoder_input,gru_inference_state_input],[dense_out,gru_state_out])
     return decoder_model

# Model Inference Class

In [ ]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np


seq2seq_model = load_model('/content/seq2seq.epoch23-val3.60886.hdf5')

# Extracting the encoder and decoder models
encoder_model = extract_encoder_model(seq2seq_model)
decoder_model = extract_decoder_model(seq2seq_model)
max_input_length=7
max_output_length=100
# Defining a function for translation using the decoder model
def translate(input_text):
    input_seq = Eng_token.texts_to_sequences([input_text])
    input_seq = pad_sequences(input_seq, maxlen=max_input_length, padding='post')

    encoder_out = encoder_model.predict(input_seq)
    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = Hindi_token.word_index['<start>']

    decoded_sentence = ''

    while True:
        output_tokens, h = decoder_model.predict([target_seq, encoder_out])

        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_token = Hindi_token.index_word[sampled_token_index]

        if sampled_token != '<end>':
            decoded_sentence += sampled_token + ' '

        target_seq = np.zeros((1, 1))
        target_seq[0, 0 ] = sampled_token_index

        encoder_out = h

        if sampled_token == '<end>' or len(decoded_sentence.split()) > max_output_length:
            break

    return decoded_sentence



# Example usage:
input_text = "Worship period "
translation = translate(input_text)
print(f"Input: {input_text}")
print(f"Translation: {translation}")


1/1 [==============================] - 0s 27ms/step
Input: Worship period 
Translation: भक्ति 
